### ISSUE TITLE
more documentation/better readme required

### ISSUE THREAD

**Issue by stenub** [victronenergy/dbus-shelly#2]
Hi there, 

i tried to install this driver to a beaglebone black running venus 2.92. I extracted the v0.4.zip zip to /data/ but i have no idea how to go on from there. I installed `make` via opkg but when i try to do a `make install` i get an error. What am I doing wrong? Is there any documentation which i have not found yet?

Kind Regards!

**Comment by LukasAusserhuber** [comment]
Hi, i also tried to run the master branch but it did not work in my case either. 
BUT i tried it to run as a "Custom Driver" like Victron described it in their VenusOS Wiki. Nothing  with make install.
This may result due to the fact that the master is not ready to use yet??

If you want to use this driver checkout the gen1 branch and install the driver as a custom driver. It works with mdns und gets all required data from the shelly.

**Comment by stenub** [comment]
Thank you Lukas for the hint! I will try this!

**Comment by stenub** [comment]
Sorry @LukasAusserhuber , but i could not find the "Custom Driver" description you are referring to. Could you please provide me with a link to the wiki and the respective section of documentation? Do you mean this wiki: https://github.com/victronenergy/venus/wiki

**Comment by LukasAusserhuber** [comment]
Oh sorry you are right. It's called "How to add a driver to venus" https://github.com/victronenergy/venus/wiki/howto-add-a-driver-to-Venus

Especially the Section "Installing a driver that doesn't depend on a serial port"

And it helps a lot to study other existing drivers which do not come as default with Venus OS.

**Comment by stenub** [comment]
i tried it out, but i get a json error. The driver detects the Shelly 3EM, connects and gets the /status json. But when the json is interpreted i get an error as the format is not the expected one by the driver. I believe that the gen1 driver is just for gen1 Shelly OS devices. I have the latest firmware running on my shelly, so perhaps this is not compatible with the driver. 

In the meantime i tried to get the main (gen2) branch running, i have managed to install pip3 and further dependencies but i struggle on installing python-openldap (which seems to be a dependency of the "secrets" module.)

The error is, that "lber.h" could not be found. All sources i found propose to install the openldap devel packages via the package manager, in this case opkg, but there seems to be no official package containing the lber.h
@izak and @jhofstee  perhaps you could give me a hint, how to get the lber.h library or openldap-dev package onto the venus os?

**Comment by LukasAusserhuber** [comment]
Just to document it, the gen1 branch in my case is running with the Shelly 3EM Fimwareversion "Current version: 20220415-105853/v1.11.7-25-gb3b096857-v1.11.7-3em"

The newest version would be "New version: 20221027-110030/v1.12.1-ga9117d3"

**Comment by stenub** [comment]
ok, i managed to install the master branch, just to find out that a Shelly 3EM is not a Gen 2 Device. There is another device called Shelly PRO 3EM whitch in fact is a Gen 2 device. So for anybody who is curious how to get the dbus-shelly for Gen2 running:

copy the contents of the zip to the /data/ directory, e.g. /data/dbus-shelly
follow the path in the ext directory to the aiovelib: https://github.com/victronenergy/aiovelib and place it in the ext dir.

try to run ./dbus-shelly inside the directory. --> it will not work, als there are some libraries missing.
Now go on and try to fix that with the following steps:

The python3.8 installation on venus os lacks a few modules.
First install pip3, then copy dataclasses.py and secrets.py to the /usr/lib/python3.8 directory, e.g.
also dbus_next is required: pip3 install dbus_next

```
wget https://raw.githubusercontent.com/python/cpython/3.8/Lib/secrets.py
wget https://raw.githubusercontent.com/python/cpython/3.8/Lib/dataclasses.py
```
then pip3 install websockets

i cannot remeber every detail which i tried, as it was very much trial and error, but that should have been the main "problems" to solve. When you try to run ./shelly-dbus and it complains about missing modules, first look if they are bundled with a standard python3.8 distribution (https://raw.githubusercontent.com/python/cpython/3.8/Lib/). If yes, copy them in the /usr/lib/python3.8 directory, if no, try to get it via pip3.
Attention: opkg search *python* delivers also many packages, which i think, should be preferred over the pip3 sourced packages.

Now i am going to delete everything and start all over with the gen1 branch....

**Comment by stenub** [comment]
done, i managed to get the gen1 driver running. The next thing i found out is, that there is no problem with the newer firmware, but with the password authentication "basic http" i have configured on the shelly. I disabled password auth, and everything runs fine. @LukasAusserhuber did you manage to get it running with password auth? If so, would you gladly give me a hint how to achieve this? i could not find any config files or something.
I also build around a service adapted from the great https://github.com/fabian-lauer/dbus-shelly-3em-smartmeter project, so that it should survive a venus os upgrade. Perhaps i will fork the gen1 branch and implement the service adaption if there is any public interest in this.

**Comment by towatai** [comment]
> there is no problem with the newer firmware, but with the password authentication "basic http" i have configured on the shelly. I disabled password auth, and everything runs fine.

Please try the following Username: admin

Thats no Joke, works for me and my Plus 1PM

**Comment by R0land82** [comment]
Hi together, i followed the installation hints from stenub. I try to start dbus_shelly.py but i got the error:

 File "./dbus_shelly.py", line 24, in <module>
    from aiovelib.service import Service
ModuleNotFoundError: No module named 'aiovelib'

Did i have to install aiovedlib as service?

I copyed the aiovelib files from git to the ext directory but it doesn't work.

Has someone a hint for me?

**Comment by stenub** [comment]
Hi, i think you forgot the following step:

follow the path in the ext directory to the aiovelib: https://github.com/victronenergy/aiovelib **and place it in the ext dir.**

**Comment by izak** [comment]
Guys, all you have to do is update the submodules. After checking it out, just call:

`git submodule update --init`

And it will check out aiovelib for you. Remember you also need python-dbus-next installed.

The module is also included in the beta releases already (which you need anyway, otherwise you won't have dbus-next), so I advise that you simply use a beta release of Venus.

Also, this code only works for the new Pro EM3 meter, released last month. If you want to mess with the gen1 driver, you are on your own.
