### ISSUE TITLE
Too many failing dependencies on VenusOS

### ISSUE THREAD

**Issue by Kudos50** [victronenergy/dbus-shelly#5]
Super pleased development is taking place but unable to make it work. On the latest standard VenusOS (2.94) I have cloned the module and submodules only to start the journey of installing dependencies:
- change root filesystem to writeable
- install opkg / pip
- install websockets

After that, all stopped. Installing secrets failed on the freshly installed dataclasses. To be more precise, the python-ldap dependency for secrets failed. Using make also fails as the required variables are not set.

As this concerns a fresh load of the latest VenosOS I was kind of hoping you can either elaborate a little in the readme or script the install in such a way that non-guru's can make it work on a Cerbo GX. To be able to use a shelly as a grid meter is a truly great feature!

**Comment by stenub** [comment]
Hi, i have been there, i know the problem with python-ldap, but please be assured, that you are on the wrong path.. I wrote a litte "documentation" on how to "resolve" the dependencies. Please have a look here: 
https://github.com/victronenergy/dbus-shelly/issues/2#issuecomment-1371472831

Please replace the first step (cloning the repo) with the following:
git submodule update --init
this makes the step with pulling the aiovelib (referenced git repo) obsolete. Reference: https://github.com/victronenergy/dbus-shelly/issues/2#issuecomment-1463956415

**Comment by Kudos50** [comment]
Many thanks. I did clone the module and submodules so that was never the issue. It's probably the copy or link action of the py files after installing the packages that's the issue. Very grateful.

But I would still love to see something that survives a firmware update like the shelly integration I'm using now.

**Comment by izak** [comment]
My advice is simply to stop hurting yourself and install a Venus 3.00 beta. It has everything you need. Closing this.
