### ISSUE TITLE
Device not showing up under Energy meters

### ISSUE THREAD

**Issue by Jalle19** [victronenergy/dbus-shelly#8]
See screenshots:
![2023-10-12_20-12](https://github.com/victronenergy/dbus-shelly/assets/1106133/e06e0716-86d8-46bb-a224-961a66b61990)
![2023-10-12_20-12_1](https://github.com/victronenergy/dbus-shelly/assets/1106133/1c70fc2f-faa7-485c-8616-740cf5b24721)

**Comment by jjdejong** [comment]
It is not supposed to show up there. This section is for another class of meters

**Comment by Jalle19** [comment]
This is apparently by design, closing
